name: "build"
on:
    push: ~

    pull_request: ~

    workflow_dispatch: ~

jobs:
    checks:
        name: "PHP ${{ matrix.php }} | SF ${{ matrix.symfony }} | Sylius ${{ matrix.sylius }}"

        runs-on: "ubuntu-latest"

        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"

                symfony:
                    - "~5.4.0"
                    - "~6.4.0"
                    - "~7.1.0"
                    - "~7.2.0"

                sylius:
                    - "~1.12.0"
                    - "~1.13.0"
                    - "~1.14.0"
                    - "~2.0.0"

                exclude:
                    -   php: "8.1"
                        sylius: "~2.0.0"
                    -   php: "8.1"
                        symfony: "~7.1.0"
                    -   php: "8.1"
                        symfony: "~7.2.0"
                    -   symfony: "~5.4.0"
                        sylius: "~2.0.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: "none"
                    tools: "flex"

            -   name: "Add Sylius dependency"
                run: "composer require --no-install --no-update --no-plugins --no-scripts sylius/sylius:${{ matrix.sylius }}"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v3"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"

            -   name: "Validate composer"
                run: "composer validate --strict"

            -   name: "Check composer normalized"
                run: "composer normalize --dry-run"
